name: animalprufrock
favicon: null
layout_spectrum: 0.5404889949131757
typography_spectrum: 0.2258555879816413
title: "'animal prufrocks transperformative arts theory'"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0076bc'
    - '#fdfef9'
    - '#ad4e2e'
    - '#fed203'
    - '#0e0a09'
  brandStrength: 0.022545853396877646
  lightness: 0.8858130879234523
  saturation: 0.28857256937772036
  rhythmicContrast: 0.08485816814936697
purpose: []
