name: animalprufrock
favicon: null
layout_spectrum: 0.5404889949131757
typography_spectrum: 0.40303
title: animal prufrocks transperformative arts theory
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0076bc'
    - '#fdfef9'
    - '#ad4e2e'
    - '#fed203'
    - '#0e0a09'
  brandStrength: 0.0625
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
